### ISSUE TITLE
sed-puzzle.com appears to be down...

### ISSUE THREAD

**Issue by Zomulgustar** [sugim48/sed-puzzle-issues#11]
If this is permanent, would it be feasible to archive the puzzles, perhaps here on github?

**Comment by sugim48** [comment]
@Zomulgustar Sorry for the late reply. Sed Puzzle is working now.

**Comment by Zomulgustar** [comment]
Thanks so much! Looking forward to getting back into it, and will take care
not to put it off too long this time. ^_^
-Andy
